
//user action types
export const FETCH_LOANS_REQ_REQUEST = 'FETCH_LOANS_REQ_REQUEST';
export const FETCH_LOANS_REQ_FAILURE = 'FETCH_LOANS_REQ_FAILURE';
export const FETCH_LOANS_REQ_SUCCESS = 'FETCH_LOANS_REQ_SUCCESS';
