
//Places action types
export const FETCH_PLACES_REQUEST = 'FETCH_PLACES_REQUEST';
export const FETCH_PLACES_FAILURE = 'FETCH_PLACES_FAILURE';
export const FETCH_PLACES_SUCCESS = 'FETCH_PLACES_SUCCESS';
